version: '3.8'
networks:
  db:
    driver: bridge

volumes:
  data:

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - '8080:8080'
    networks:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hybridvision
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=
      - DATA_INIT=true
      - DDL=validate

  db:
    container_name: database
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=hybridvision
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    networks:
      - db
    volumes:
      - data:/var/lib/postgresql/data

